// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportCast.Server.Infrastructure.Data;

#nullable disable

namespace SportCast.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117205031_SeedNbaTeams")]
    partial class SeedNbaTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authentication")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "authentication");
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsersId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "authentication");
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("SportsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SportsId");

                    b.ToTable("Sports", "sport");

                    b.HasData(
                        new
                        {
                            SportsId = 1,
                            Name = "NFL"
                        },
                        new
                        {
                            SportsId = 2,
                            Name = "MLB"
                        },
                        new
                        {
                            SportsId = 3,
                            Name = "NBA"
                        },
                        new
                        {
                            SportsId = 4,
                            Name = "MLS"
                        },
                        new
                        {
                            SportsId = 5,
                            Name = "NCAA Football"
                        },
                        new
                        {
                            SportsId = 6,
                            Name = "NCAA Basketball"
                        },
                        new
                        {
                            SportsId = 7,
                            Name = "NCAA Baseball"
                        });
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("TeamId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams", "sport");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            LocationName = "Atlanta",
                            SportId = 3,
                            TeamName = "Hawks"
                        },
                        new
                        {
                            TeamId = 2,
                            LocationName = "Boston",
                            SportId = 3,
                            TeamName = "Celtics"
                        },
                        new
                        {
                            TeamId = 3,
                            LocationName = "Brooklyn",
                            SportId = 3,
                            TeamName = "Nets"
                        },
                        new
                        {
                            TeamId = 4,
                            LocationName = "Charlotte",
                            SportId = 3,
                            TeamName = "Hornets"
                        },
                        new
                        {
                            TeamId = 5,
                            LocationName = "Chicago",
                            SportId = 3,
                            TeamName = "Bulls"
                        },
                        new
                        {
                            TeamId = 6,
                            LocationName = "Cleveland",
                            SportId = 3,
                            TeamName = "Cavaliers"
                        },
                        new
                        {
                            TeamId = 7,
                            LocationName = "Dallas",
                            SportId = 3,
                            TeamName = "Mavericks"
                        },
                        new
                        {
                            TeamId = 8,
                            LocationName = "Denver",
                            SportId = 3,
                            TeamName = "Nuggets"
                        },
                        new
                        {
                            TeamId = 9,
                            LocationName = "Detroit",
                            SportId = 3,
                            TeamName = "Pistons"
                        },
                        new
                        {
                            TeamId = 10,
                            LocationName = "Golden State",
                            SportId = 3,
                            TeamName = "Warriors"
                        },
                        new
                        {
                            TeamId = 11,
                            LocationName = "Houston",
                            SportId = 3,
                            TeamName = "Rockets"
                        },
                        new
                        {
                            TeamId = 12,
                            LocationName = "Indiana",
                            SportId = 3,
                            TeamName = "Pacers"
                        },
                        new
                        {
                            TeamId = 13,
                            LocationName = "Los Angeles",
                            SportId = 3,
                            TeamName = "Clippers"
                        },
                        new
                        {
                            TeamId = 14,
                            LocationName = "Los Angeles",
                            SportId = 3,
                            TeamName = "Lakers"
                        },
                        new
                        {
                            TeamId = 15,
                            LocationName = "Memphis",
                            SportId = 3,
                            TeamName = "Grizzlies"
                        },
                        new
                        {
                            TeamId = 16,
                            LocationName = "Miami",
                            SportId = 3,
                            TeamName = "Heat"
                        },
                        new
                        {
                            TeamId = 17,
                            LocationName = "Milwaukee",
                            SportId = 3,
                            TeamName = "Bucks"
                        },
                        new
                        {
                            TeamId = 18,
                            LocationName = "Minnesota",
                            SportId = 3,
                            TeamName = "Timberwolves"
                        },
                        new
                        {
                            TeamId = 19,
                            LocationName = "New Orleans",
                            SportId = 3,
                            TeamName = "Pelicans"
                        },
                        new
                        {
                            TeamId = 20,
                            LocationName = "New York",
                            SportId = 3,
                            TeamName = "Knicks"
                        },
                        new
                        {
                            TeamId = 21,
                            LocationName = "Oklahoma City",
                            SportId = 3,
                            TeamName = "Thunder"
                        },
                        new
                        {
                            TeamId = 22,
                            LocationName = "Orlando",
                            SportId = 3,
                            TeamName = "Magic"
                        },
                        new
                        {
                            TeamId = 23,
                            LocationName = "Philadelphia",
                            SportId = 3,
                            TeamName = "76ers"
                        },
                        new
                        {
                            TeamId = 24,
                            LocationName = "Phoenix",
                            SportId = 3,
                            TeamName = "Suns"
                        },
                        new
                        {
                            TeamId = 25,
                            LocationName = "Portland",
                            SportId = 3,
                            TeamName = "Trail Blazers"
                        },
                        new
                        {
                            TeamId = 26,
                            LocationName = "Sacramento",
                            SportId = 3,
                            TeamName = "Kings"
                        },
                        new
                        {
                            TeamId = 27,
                            LocationName = "San Antonio",
                            SportId = 3,
                            TeamName = "Spurs"
                        },
                        new
                        {
                            TeamId = 28,
                            LocationName = "Toronto",
                            SportId = 3,
                            TeamName = "Raptors"
                        },
                        new
                        {
                            TeamId = 29,
                            LocationName = "Utah",
                            SportId = 3,
                            TeamName = "Jazz"
                        },
                        new
                        {
                            TeamId = 30,
                            LocationName = "Washington",
                            SportId = 3,
                            TeamName = "Wizards"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Team", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
