// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportCast.Server.Infrastructure.Data;

#nullable disable

namespace SportCast.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117205530_SeedMlsTeams")]
    partial class SeedMlsTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authentication")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "authentication");
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsersId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "authentication");
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("SportsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SportsId");

                    b.ToTable("Sports", "sport");

                    b.HasData(
                        new
                        {
                            SportsId = 1,
                            Name = "NFL"
                        },
                        new
                        {
                            SportsId = 2,
                            Name = "MLB"
                        },
                        new
                        {
                            SportsId = 3,
                            Name = "NBA"
                        },
                        new
                        {
                            SportsId = 4,
                            Name = "MLS"
                        },
                        new
                        {
                            SportsId = 5,
                            Name = "NCAA Football"
                        },
                        new
                        {
                            SportsId = 6,
                            Name = "NCAA Basketball"
                        },
                        new
                        {
                            SportsId = 7,
                            Name = "NCAA Baseball"
                        });
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("TeamId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams", "sport");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            LocationName = "Atlanta",
                            SportId = 3,
                            TeamName = "Hawks"
                        },
                        new
                        {
                            TeamId = 2,
                            LocationName = "Boston",
                            SportId = 3,
                            TeamName = "Celtics"
                        },
                        new
                        {
                            TeamId = 3,
                            LocationName = "Brooklyn",
                            SportId = 3,
                            TeamName = "Nets"
                        },
                        new
                        {
                            TeamId = 4,
                            LocationName = "Charlotte",
                            SportId = 3,
                            TeamName = "Hornets"
                        },
                        new
                        {
                            TeamId = 5,
                            LocationName = "Chicago",
                            SportId = 3,
                            TeamName = "Bulls"
                        },
                        new
                        {
                            TeamId = 6,
                            LocationName = "Cleveland",
                            SportId = 3,
                            TeamName = "Cavaliers"
                        },
                        new
                        {
                            TeamId = 7,
                            LocationName = "Dallas",
                            SportId = 3,
                            TeamName = "Mavericks"
                        },
                        new
                        {
                            TeamId = 8,
                            LocationName = "Denver",
                            SportId = 3,
                            TeamName = "Nuggets"
                        },
                        new
                        {
                            TeamId = 9,
                            LocationName = "Detroit",
                            SportId = 3,
                            TeamName = "Pistons"
                        },
                        new
                        {
                            TeamId = 10,
                            LocationName = "Golden State",
                            SportId = 3,
                            TeamName = "Warriors"
                        },
                        new
                        {
                            TeamId = 11,
                            LocationName = "Houston",
                            SportId = 3,
                            TeamName = "Rockets"
                        },
                        new
                        {
                            TeamId = 12,
                            LocationName = "Indiana",
                            SportId = 3,
                            TeamName = "Pacers"
                        },
                        new
                        {
                            TeamId = 13,
                            LocationName = "Los Angeles",
                            SportId = 3,
                            TeamName = "Clippers"
                        },
                        new
                        {
                            TeamId = 14,
                            LocationName = "Los Angeles",
                            SportId = 3,
                            TeamName = "Lakers"
                        },
                        new
                        {
                            TeamId = 15,
                            LocationName = "Memphis",
                            SportId = 3,
                            TeamName = "Grizzlies"
                        },
                        new
                        {
                            TeamId = 16,
                            LocationName = "Miami",
                            SportId = 3,
                            TeamName = "Heat"
                        },
                        new
                        {
                            TeamId = 17,
                            LocationName = "Milwaukee",
                            SportId = 3,
                            TeamName = "Bucks"
                        },
                        new
                        {
                            TeamId = 18,
                            LocationName = "Minnesota",
                            SportId = 3,
                            TeamName = "Timberwolves"
                        },
                        new
                        {
                            TeamId = 19,
                            LocationName = "New Orleans",
                            SportId = 3,
                            TeamName = "Pelicans"
                        },
                        new
                        {
                            TeamId = 20,
                            LocationName = "New York",
                            SportId = 3,
                            TeamName = "Knicks"
                        },
                        new
                        {
                            TeamId = 21,
                            LocationName = "Oklahoma City",
                            SportId = 3,
                            TeamName = "Thunder"
                        },
                        new
                        {
                            TeamId = 22,
                            LocationName = "Orlando",
                            SportId = 3,
                            TeamName = "Magic"
                        },
                        new
                        {
                            TeamId = 23,
                            LocationName = "Philadelphia",
                            SportId = 3,
                            TeamName = "76ers"
                        },
                        new
                        {
                            TeamId = 24,
                            LocationName = "Phoenix",
                            SportId = 3,
                            TeamName = "Suns"
                        },
                        new
                        {
                            TeamId = 25,
                            LocationName = "Portland",
                            SportId = 3,
                            TeamName = "Trail Blazers"
                        },
                        new
                        {
                            TeamId = 26,
                            LocationName = "Sacramento",
                            SportId = 3,
                            TeamName = "Kings"
                        },
                        new
                        {
                            TeamId = 27,
                            LocationName = "San Antonio",
                            SportId = 3,
                            TeamName = "Spurs"
                        },
                        new
                        {
                            TeamId = 28,
                            LocationName = "Toronto",
                            SportId = 3,
                            TeamName = "Raptors"
                        },
                        new
                        {
                            TeamId = 29,
                            LocationName = "Utah",
                            SportId = 3,
                            TeamName = "Jazz"
                        },
                        new
                        {
                            TeamId = 30,
                            LocationName = "Washington",
                            SportId = 3,
                            TeamName = "Wizards"
                        },
                        new
                        {
                            TeamId = 31,
                            LocationName = "Arizona",
                            SportId = 1,
                            TeamName = "Cardinals"
                        },
                        new
                        {
                            TeamId = 32,
                            LocationName = "Atlanta",
                            SportId = 1,
                            TeamName = "Falcons"
                        },
                        new
                        {
                            TeamId = 33,
                            LocationName = "Baltimore",
                            SportId = 1,
                            TeamName = "Ravens"
                        },
                        new
                        {
                            TeamId = 34,
                            LocationName = "Buffalo",
                            SportId = 1,
                            TeamName = "Bills"
                        },
                        new
                        {
                            TeamId = 35,
                            LocationName = "Carolina",
                            SportId = 1,
                            TeamName = "Panthers"
                        },
                        new
                        {
                            TeamId = 36,
                            LocationName = "Chicago",
                            SportId = 1,
                            TeamName = "Bears"
                        },
                        new
                        {
                            TeamId = 37,
                            LocationName = "Cincinnati",
                            SportId = 1,
                            TeamName = "Bengals"
                        },
                        new
                        {
                            TeamId = 38,
                            LocationName = "Cleveland",
                            SportId = 1,
                            TeamName = "Browns"
                        },
                        new
                        {
                            TeamId = 39,
                            LocationName = "Dallas",
                            SportId = 1,
                            TeamName = "Cowboys"
                        },
                        new
                        {
                            TeamId = 40,
                            LocationName = "Denver",
                            SportId = 1,
                            TeamName = "Broncos"
                        },
                        new
                        {
                            TeamId = 41,
                            LocationName = "Detroit",
                            SportId = 1,
                            TeamName = "Lions"
                        },
                        new
                        {
                            TeamId = 42,
                            LocationName = "Green Bay",
                            SportId = 1,
                            TeamName = "Packers"
                        },
                        new
                        {
                            TeamId = 43,
                            LocationName = "Houston",
                            SportId = 1,
                            TeamName = "Texans"
                        },
                        new
                        {
                            TeamId = 44,
                            LocationName = "Indianapolis",
                            SportId = 1,
                            TeamName = "Colts"
                        },
                        new
                        {
                            TeamId = 45,
                            LocationName = "Jacksonville",
                            SportId = 1,
                            TeamName = "Jaguars"
                        },
                        new
                        {
                            TeamId = 46,
                            LocationName = "Kansas City",
                            SportId = 1,
                            TeamName = "Chiefs"
                        },
                        new
                        {
                            TeamId = 47,
                            LocationName = "Las Vegas",
                            SportId = 1,
                            TeamName = "Raiders"
                        },
                        new
                        {
                            TeamId = 48,
                            LocationName = "Los Angeles",
                            SportId = 1,
                            TeamName = "Chargers"
                        },
                        new
                        {
                            TeamId = 49,
                            LocationName = "Los Angeles",
                            SportId = 1,
                            TeamName = "Rams"
                        },
                        new
                        {
                            TeamId = 50,
                            LocationName = "Miami",
                            SportId = 1,
                            TeamName = "Dolphins"
                        },
                        new
                        {
                            TeamId = 51,
                            LocationName = "Minnesota",
                            SportId = 1,
                            TeamName = "Vikings"
                        },
                        new
                        {
                            TeamId = 52,
                            LocationName = "New England",
                            SportId = 1,
                            TeamName = "Patriots"
                        },
                        new
                        {
                            TeamId = 53,
                            LocationName = "New Orleans",
                            SportId = 1,
                            TeamName = "Saints"
                        },
                        new
                        {
                            TeamId = 54,
                            LocationName = "New York",
                            SportId = 1,
                            TeamName = "Giants"
                        },
                        new
                        {
                            TeamId = 55,
                            LocationName = "New York",
                            SportId = 1,
                            TeamName = "Jets"
                        },
                        new
                        {
                            TeamId = 56,
                            LocationName = "Philadelphia",
                            SportId = 1,
                            TeamName = "Eagles"
                        },
                        new
                        {
                            TeamId = 57,
                            LocationName = "Pittsburgh",
                            SportId = 1,
                            TeamName = "Steelers"
                        },
                        new
                        {
                            TeamId = 58,
                            LocationName = "San Francisco",
                            SportId = 1,
                            TeamName = "49ers"
                        },
                        new
                        {
                            TeamId = 59,
                            LocationName = "Seattle",
                            SportId = 1,
                            TeamName = "Seahawks"
                        },
                        new
                        {
                            TeamId = 60,
                            LocationName = "Tampa Bay",
                            SportId = 1,
                            TeamName = "Buccaneers"
                        },
                        new
                        {
                            TeamId = 61,
                            LocationName = "Tennessee",
                            SportId = 1,
                            TeamName = "Titans"
                        },
                        new
                        {
                            TeamId = 62,
                            LocationName = "Washington",
                            SportId = 1,
                            TeamName = "Commanders"
                        },
                        new
                        {
                            TeamId = 63,
                            LocationName = "Arizona",
                            SportId = 2,
                            TeamName = "Diamondbacks"
                        },
                        new
                        {
                            TeamId = 64,
                            LocationName = "Atlanta",
                            SportId = 2,
                            TeamName = "Braves"
                        },
                        new
                        {
                            TeamId = 65,
                            LocationName = "Baltimore",
                            SportId = 2,
                            TeamName = "Orioles"
                        },
                        new
                        {
                            TeamId = 66,
                            LocationName = "Boston",
                            SportId = 2,
                            TeamName = "Red Sox"
                        },
                        new
                        {
                            TeamId = 67,
                            LocationName = "Chicago",
                            SportId = 2,
                            TeamName = "Cubs"
                        },
                        new
                        {
                            TeamId = 68,
                            LocationName = "Chicago",
                            SportId = 2,
                            TeamName = "White Sox"
                        },
                        new
                        {
                            TeamId = 69,
                            LocationName = "Cincinnati",
                            SportId = 2,
                            TeamName = "Reds"
                        },
                        new
                        {
                            TeamId = 70,
                            LocationName = "Cleveland",
                            SportId = 2,
                            TeamName = "Guardians"
                        },
                        new
                        {
                            TeamId = 71,
                            LocationName = "Colorado",
                            SportId = 2,
                            TeamName = "Rockies"
                        },
                        new
                        {
                            TeamId = 72,
                            LocationName = "Detroit",
                            SportId = 2,
                            TeamName = "Tigers"
                        },
                        new
                        {
                            TeamId = 73,
                            LocationName = "Houston",
                            SportId = 2,
                            TeamName = "Astros"
                        },
                        new
                        {
                            TeamId = 74,
                            LocationName = "Kansas City",
                            SportId = 2,
                            TeamName = "Royals"
                        },
                        new
                        {
                            TeamId = 75,
                            LocationName = "Los Angeles",
                            SportId = 2,
                            TeamName = "Angels"
                        },
                        new
                        {
                            TeamId = 76,
                            LocationName = "Los Angeles",
                            SportId = 2,
                            TeamName = "Dodgers"
                        },
                        new
                        {
                            TeamId = 77,
                            LocationName = "Miami",
                            SportId = 2,
                            TeamName = "Marlins"
                        },
                        new
                        {
                            TeamId = 78,
                            LocationName = "Milwaukee",
                            SportId = 2,
                            TeamName = "Brewers"
                        },
                        new
                        {
                            TeamId = 79,
                            LocationName = "Minnesota",
                            SportId = 2,
                            TeamName = "Twins"
                        },
                        new
                        {
                            TeamId = 80,
                            LocationName = "New York",
                            SportId = 2,
                            TeamName = "Mets"
                        },
                        new
                        {
                            TeamId = 81,
                            LocationName = "New York",
                            SportId = 2,
                            TeamName = "Yankees"
                        },
                        new
                        {
                            TeamId = 82,
                            LocationName = "Oakland",
                            SportId = 2,
                            TeamName = "Athletics"
                        },
                        new
                        {
                            TeamId = 83,
                            LocationName = "Philadelphia",
                            SportId = 2,
                            TeamName = "Phillies"
                        },
                        new
                        {
                            TeamId = 84,
                            LocationName = "Pittsburgh",
                            SportId = 2,
                            TeamName = "Pirates"
                        },
                        new
                        {
                            TeamId = 85,
                            LocationName = "San Diego",
                            SportId = 2,
                            TeamName = "Padres"
                        },
                        new
                        {
                            TeamId = 86,
                            LocationName = "San Francisco",
                            SportId = 2,
                            TeamName = "Giants"
                        },
                        new
                        {
                            TeamId = 87,
                            LocationName = "Seattle",
                            SportId = 2,
                            TeamName = "Mariners"
                        },
                        new
                        {
                            TeamId = 88,
                            LocationName = "St. Louis",
                            SportId = 2,
                            TeamName = "Cardinals"
                        },
                        new
                        {
                            TeamId = 89,
                            LocationName = "Tampa Bay",
                            SportId = 2,
                            TeamName = "Rays"
                        },
                        new
                        {
                            TeamId = 90,
                            LocationName = "Texas",
                            SportId = 2,
                            TeamName = "Rangers"
                        },
                        new
                        {
                            TeamId = 91,
                            LocationName = "Toronto",
                            SportId = 2,
                            TeamName = "Blue Jays"
                        },
                        new
                        {
                            TeamId = 92,
                            LocationName = "Washington",
                            SportId = 2,
                            TeamName = "Nationals"
                        },
                        new
                        {
                            TeamId = 93,
                            LocationName = "Atlanta",
                            SportId = 4,
                            TeamName = "United"
                        },
                        new
                        {
                            TeamId = 94,
                            LocationName = "Austin",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 95,
                            LocationName = "Charlotte",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 96,
                            LocationName = "Chicago",
                            SportId = 4,
                            TeamName = "Fire"
                        },
                        new
                        {
                            TeamId = 97,
                            LocationName = "Cincinnati",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 98,
                            LocationName = "Colorado",
                            SportId = 4,
                            TeamName = "Rapids"
                        },
                        new
                        {
                            TeamId = 99,
                            LocationName = "Columbus",
                            SportId = 4,
                            TeamName = "Crew"
                        },
                        new
                        {
                            TeamId = 100,
                            LocationName = "Dallas",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 101,
                            LocationName = "D.C. United",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 102,
                            LocationName = "Houston",
                            SportId = 4,
                            TeamName = "Dynamo"
                        },
                        new
                        {
                            TeamId = 103,
                            LocationName = "Kansas City",
                            SportId = 4,
                            TeamName = "Sporting"
                        },
                        new
                        {
                            TeamId = 104,
                            LocationName = "Los Angeles",
                            SportId = 4,
                            TeamName = "Galaxy"
                        },
                        new
                        {
                            TeamId = 105,
                            LocationName = "Los Angeles",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 106,
                            LocationName = "Miami",
                            SportId = 4,
                            TeamName = "Inter"
                        },
                        new
                        {
                            TeamId = 107,
                            LocationName = "Minnesota",
                            SportId = 4,
                            TeamName = "United"
                        },
                        new
                        {
                            TeamId = 108,
                            LocationName = "Montreal",
                            SportId = 4,
                            TeamName = "CF"
                        },
                        new
                        {
                            TeamId = 109,
                            LocationName = "Nashville",
                            SportId = 4,
                            TeamName = "SC"
                        },
                        new
                        {
                            TeamId = 110,
                            LocationName = "New England",
                            SportId = 4,
                            TeamName = "Revolution"
                        },
                        new
                        {
                            TeamId = 111,
                            LocationName = "New York City",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 112,
                            LocationName = "New York",
                            SportId = 4,
                            TeamName = "Red Bulls"
                        },
                        new
                        {
                            TeamId = 113,
                            LocationName = "Orlando",
                            SportId = 4,
                            TeamName = "City"
                        },
                        new
                        {
                            TeamId = 114,
                            LocationName = "Philadelphia",
                            SportId = 4,
                            TeamName = "Union"
                        },
                        new
                        {
                            TeamId = 115,
                            LocationName = "Portland",
                            SportId = 4,
                            TeamName = "Timbers"
                        },
                        new
                        {
                            TeamId = 116,
                            LocationName = "Salt Lake",
                            SportId = 4,
                            TeamName = "Real"
                        },
                        new
                        {
                            TeamId = 117,
                            LocationName = "San Jose",
                            SportId = 4,
                            TeamName = "Earthquakes"
                        },
                        new
                        {
                            TeamId = 118,
                            LocationName = "Seattle",
                            SportId = 4,
                            TeamName = "Sounders"
                        },
                        new
                        {
                            TeamId = 119,
                            LocationName = "St. Louis",
                            SportId = 4,
                            TeamName = "City"
                        },
                        new
                        {
                            TeamId = 120,
                            LocationName = "Toronto",
                            SportId = 4,
                            TeamName = "FC"
                        },
                        new
                        {
                            TeamId = 121,
                            LocationName = "Vancouver",
                            SportId = 4,
                            TeamName = "Whitecaps"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportCast.Server.Domain.Entities.Team", b =>
                {
                    b.HasOne("SportCast.Server.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
